#!/bin/bash
# Test script for Email Service

set -e

# Colors for output
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Configuration
EMAIL_SERVICE_URL="${EMAIL_SERVICE_URL:-http://localhost:8309}"
TEST_RECIPIENT="${TEST_RECIPIENT:-ljiahao@fortinet.com}"

echo -e "${YELLOW}========================================${NC}"
echo -e "${YELLOW}  Email Service Test Suite${NC}"
echo -e "${YELLOW}========================================${NC}"
echo ""
echo "Email Service URL: $EMAIL_SERVICE_URL"
echo "Test Recipient: $TEST_RECIPIENT"
echo ""

# Function to test endpoint
test_endpoint() {
    local name=$1
    local method=$2
    local endpoint=$3
    local data=$4

    echo -e "${YELLOW}Testing: $name${NC}"

    if [ -z "$data" ]; then
        response=$(curl -s -w "\n%{http_code}" "$EMAIL_SERVICE_URL$endpoint")
    else
        response=$(curl -s -w "\n%{http_code}" -X "$method" "$EMAIL_SERVICE_URL$endpoint" \
            -H "Content-Type: application/json" \
            -d "$data")
    fi

    http_code=$(echo "$response" | tail -n1)
    body=$(echo "$response" | sed '$d')

    if [ "$http_code" -eq 200 ] || [ "$http_code" -eq 201 ]; then
        echo -e "${GREEN}✓ PASSED${NC} (HTTP $http_code)"
        echo "Response: $body"
    else
        echo -e "${RED}✗ FAILED${NC} (HTTP $http_code)"
        echo "Response: $body"
        return 1
    fi
    echo ""
}

# Test 1: Health Check
test_endpoint "Health Check" "GET" "/health"

# Test 2: Readiness Check (includes SMTP verification)
test_endpoint "Readiness Check" "GET" "/ready"

# Test 3: Send Test Email
echo -e "${YELLOW}Test 3: Send Test Email${NC}"
read -p "Do you want to send a test email to $TEST_RECIPIENT? (y/n) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    test_endpoint "Send Test Email" "POST" "/send-test-email" "{\"recipient\":\"$TEST_RECIPIENT\"}"
else
    echo -e "${YELLOW}Skipped${NC}"
    echo ""
fi

# Test 4: Send Error Report
echo -e "${YELLOW}Test 4: Send Error Report${NC}"
read -p "Do you want to send a test error report to $TEST_RECIPIENT? (y/n) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    error_data=$(cat <<EOF
{
  "title": "Test Error Report - Email Service Test",
  "content": "This is an automated test error report generated by the test script.\n\nDetails:\n- Test ID: $(date +%s)\n- Environment: Development\n- Status: Testing email functionality\n\nThis message can be safely ignored.",
  "category": "Infrastructure",
  "recipient": "$TEST_RECIPIENT"
}
EOF
)
    test_endpoint "Send Error Report" "POST" "/send-error-report" "$error_data"
else
    echo -e "${YELLOW}Skipped${NC}"
    echo ""
fi

# Test 5: Invalid Request (should fail)
echo -e "${YELLOW}Test 5: Invalid Request (Expected to Fail)${NC}"
if ! test_endpoint "Invalid Request" "POST" "/send-error-report" '{"invalid":"data"}'; then
    echo -e "${GREEN}✓ Correctly rejected invalid request${NC}"
else
    echo -e "${RED}✗ Should have rejected invalid request${NC}"
fi
echo ""

# Test 6: 404 Endpoint
echo -e "${YELLOW}Test 6: 404 Not Found (Expected to Fail)${NC}"
if ! test_endpoint "404 Endpoint" "GET" "/nonexistent"; then
    echo -e "${GREEN}✓ Correctly returned 404${NC}"
else
    echo -e "${RED}✗ Should have returned 404${NC}"
fi
echo ""

echo -e "${YELLOW}========================================${NC}"
echo -e "${GREEN}  Test Suite Complete!${NC}"
echo -e "${YELLOW}========================================${NC}"
echo ""
echo "Next Steps:"
echo "1. Check your email at $TEST_RECIPIENT"
echo "2. Verify emails were received with proper formatting"
echo "3. Review logs: kubectl logs -l app=email-service"
echo ""
